### ISSUE TITLE
File saving takes multiple seconds

### ISSUE THREAD

**Issue by ynnadkrap** [Quramy/tsuquyomi#241]
Hi,

I'm running into issues where saving a .ts file will cause vim to freeze for a few seconds. It doesn't always happen, but it happens more often than not. 

vim version
`VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 13 2018 21:01:05)`

profile.log
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    2   7.603904   0.000071  tsuquyomi#reloadAndGeterr()
    2   7.603768   0.000104  tsuquyomi#geterr()
    2   7.603664   0.000381  tsuquyomi#createFixlist()
    2   7.602379   0.000133  tsuquyomi#tsClient#tsGeterr()
    2   7.602218   0.000472  tsuquyomi#tsClient#sendCommandSyncEvents()
    2   7.599539   7.599446  tsuquyomi#tsClient#sendRequest()
   38   0.043134   0.001774  <SNR>138_VimOutputCallback()
   38   0.039921   0.000871  <SNR>139_HandleCommandMessage()
   38   0.038612   0.003276  ale#lsp#HandleMessage()
   48   0.026647   0.001670  ale#engine#HandleLSPResponse()
   18   0.026341   0.000855  ale#CallWithCooldown()
   30   0.024977   0.015433  <SNR>96_HandleTSServerDiagnostics()
   11   0.019284             <SNR>75_Highlight_Matching_Pair()
    2   0.012150   0.000167  ale#events#SaveEvent()
    2   0.011819   0.000069  ale#Queue()
    2   0.011625   0.000231  <SNR>63_ALEQueueImpl()
    2   0.009969   0.000058  ale#Lint()
    2   0.009782   0.000285  <SNR>63_ALELintImpl()
    6   0.009380   0.000301  ale#engine#HandleLoclist()
    2   0.008206   0.000522  ale#engine#RunLinters()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
    2   7.599539   7.599446  tsuquyomi#tsClient#sendRequest()
   11              0.019284  <SNR>75_Highlight_Matching_Pair()
   30   0.024977   0.015433  <SNR>96_HandleTSServerDiagnostics()
   38              0.007078  ale#lsp#ReadMessageData()
    2              0.006193  <SNR>2_StripTrailingWhitespaces()
    2              0.004118  prettier#Autoformat()
   38   0.038612   0.003276  ale#lsp#HandleMessage()
  109              0.002901  ale#Var()
    6              0.002614  ale#path#FindNearestFile()
   34   0.002645   0.002126  <SNR>27_repo_head_ref()
   68              0.001881  <SNR>27_repo()
   24   0.003746   0.001786  ale#ShouldDoNothing()
   38   0.043134   0.001774  <SNR>138_VimOutputCallback()
   48   0.026647   0.001670  ale#engine#HandleLSPResponse()
   11   0.002360   0.001605  <SNR>93_OnCursorMovedNormalMode()
   34   0.005983   0.001547  <SNR>27_repo_head()
    6              0.001415  ale#sign#ParseSigns()
    4   0.002000   0.001298  ale#linter#Get()
   48              0.001198  ale#lsp#HandleOtherInitializeResponses()
   38              0.001060  ale#job#ParseVim8ProcessID()

```

this line in the function seems to be the culript:
`   30              7.594757       let out = ch_readraw(s:tsq['channel'])`

Any advice? Thanks.

**Comment by LukasKraushofer** [comment]
I inspected the code today myself but didn't really found a related call to vims ```job_start()``` when sendRequest() ist called.

Maybe there is a problem or wrong usage of vims async functions?

**Comment by etiennecrb** [comment]
Hello! I have the same issue, since a few days **every time** I save a file the UI is blocked for about 5 seconds... Any idea?

**Comment by LukasKraushofer** [comment]
I think you got 2 problems
 1. Tsu is somehow blocking and is not working async (sadly, thats the problem we all have)
 2. You are using some TS features which slows down the ts compiler, maybe some generics? Try `tsc --statistic` on your current branch and the one you havent got the tsu blocking issues. I assume the older branch compiles much faster and thats the reason you dont see tsu blocking

**Comment by ncphillips** [comment]
Has anyone had a chance to dig into this? 

This is definitely my biggest complaints about TS development with Vim right now.

**Comment by ncphillips** [comment]
This issue is making developing with Tsuquyomi unbearable. Is there at least a way to turn off type-checking on save?

**Comment by ynnadkrap** [comment]
Disabling on save: `let g:tsuquyomi_disable_quickfix = 1`

**Comment by artemave** [comment]
My vim hangs forever for what appears to be the similar problem (I am running `TsuGeterrProject`).

Below are the logs after killing vim:

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    1 3627.197492   0.000406  tsuquyomi#geterrProject()
    2 3627.168239 3626.706031  tsuquyomi#tsClient#sendRequest()
    1 3627.166129   0.000167  tsuquyomi#tsClient#tsGeterrForProject()
    1 3627.165940   0.008024  tsuquyomi#tsClient#sendCommandSyncEvents()
 2216   0.462053   0.445409  <SNR>186_decode()
    2   0.316612   0.000435  <SNR>101_airline_refresh()
    6   0.287930   0.036009  airline#highlighter#highlight()
    2   0.242604   0.000483  airline#load_theme()
  460   0.232141   0.092738  airline#highlighter#exec()
  740   0.198687   0.126927  airline#highlighter#get_highlight()
    2   0.176237   0.000342  airline#highlighter#load_theme()
  116   0.156426   0.020337  <SNR>156_exec_separator()
    4   0.134569   0.000835  airline#update_statusline()
    4   0.133479   0.000604  <SNR>142_invoke_funcrefs()
    4   0.120591   0.010158  269()
   11   0.116991   0.003007  airline#check_mode()
   24   0.093118   0.002871  <SNR>159_get_seperator()
   28   0.084448   0.004326  <SNR>159_get_transitioned_seperator()
   56   0.080122   0.003316  airline#highlighter#add_separator()
  232   0.077289   0.014264  airline#themes#get_highlight()
```

```
FUNCTION  tsuquyomi#tsClient#sendRequest()
Called 2 times
Total time: 3627.168239
 Self time: 3626.706031

count  total (s)   self (s)
                              "call s:debugLog('called! '.a:line)
    2   0.000272   0.000117   call tsuquyomi#tsClient#startTss()
    2              0.000006   if !s:is_vim8 || g:tsuquyomi_use_vimproc
                                call s:P.writeln(s:tsq, a:line)
                              else
    2              0.000064     call ch_sendraw(s:tsq['channel'], a:line."\n")
    2              0.000002   endif
                            
    2              0.000005   let l:retry = 0
    2              0.000003   let response_list = []
                            
 8437              0.041755   while len(response_list) < a:response_length
 8436              0.026571     if !s:is_vim8 || g:tsuquyomi_use_vimproc
                                  let [out, err, type] = s:P.read_wait(s:tsq, a:delay, ['Content-Length: \d\+'])
                                  call s:debugLog('out: '.out.', type:'.type)
                                  if type == 'timedout'
                                    let retry_delay = 0.05
                                    while l:retry < a:retry_count
                                      let [out, err, type] = s:P.read_wait(s:tsq, retry_delay, ['Content-Length: \d\+'])
                                      if type == 'matched'
                                        call tsuquyomi#perfLogger#record('tssMatched')
                                        "call s:debugLog('retry: '.l:retry.', length: '.len(response_list))
                                        break
                                      endif
                                      let l:retry = l:retry + 1
                                      call tsuquyomi#perfLogger#record('tssRetry:'.l:retry)
                                    endwhile
                                  endif
                                else
 8436            3625.078920       let out = ch_readraw(s:tsq['channel'])
 8436              0.054839       let type = 'matched'
 8436              0.015560     endif
 8436              0.033958     if type == 'matched'
...
```

**Comment by kostia** [comment]
Same here - vim is blocked for around 5 seconds every time I save a TS file.

**Comment by DGmip** [comment]
I am getting a major slowdown since I updated the plugin when running TsuGetErr. It used to be instant and now, on occasion, takes a few seconds, which makes working with this plugin much slower.

**Comment by jjmurre** [comment]
For me the latest version with this PR included (2a3dcbc9085975c3b1c49c382f6c87c69d199a44) does not help, my vim still hangs for several seconds on save and CPU useage goes to 100 % during save.
