### ISSUE TITLE
Balloon only shows '0'

### ISSUE THREAD

**Issue by OliverJAsh** [Quramy/tsuquyomi#73]
I have `set ballooneval`. When using MacVim, I only get `0` in my tooltip:

![image](https://cloud.githubusercontent.com/assets/921609/16282253/dc67b670-38bf-11e6-90e7-2c6b8725624a.png)

I believe this is because we don't specify the path to the file, only the filename:

```
  let l:filename = buffer_name(v:beval_bufnr)
  let res = tsuquyomi#tsClient#tsQuickinfo(l:filename, v:beval_lnum, v:beval_col)
```

Any ideas how we can get the full path to the given buffer? I'm new to vim :-)

**Comment by Quramy** [comment]
I tried to reproduce it , but I couldn't...

Please try confirm the following cmd in your MacVim.

```vim
:echo buffer_name(v:beval_bufnr)
```

**Comment by OliverJAsh** [comment]
Yesterday I was seeing this: `l:filename` ends up as `main.ts`. When I do `:echo tsuquyomi#tsClient#tsQuickinfo('main.ts', 5, 1) ` I get `{}` in response. When I do `:echo tsuquyomi#tsClient#tsQuickinfo(expand('%:p'), 5, 1)` where the expand resolves to the same file but with a full path: `/Users/OliverJAsh/Development/typescript-playground/main.ts` then I get the correct response `{ 'displayString': '…' } …`.

However today it seems to work, and the buffer name ends up as the full path. Odd!

**Comment by OliverJAsh** [comment]
When I open a file directly like `mvim main.ts`, then `:echo buffer_name(v:beval_bufnr)` is `main.ts`, not the whole path, which causes the `0` to show in the tooltip.

**Comment by OliverJAsh** [comment]
Sometimes I only get the file name, sometimes I get the whole path, sometimes I get the dir name.

**Comment by Quramy** [comment]
Sorry, `expand:('%:p')` should be used. I've fixed it. Please check out it.

**Comment by Quramy** [comment]
Thanks for your reporting and review :)

**Comment by OliverJAsh** [comment]
Works now, thank you! BTW I still get 0 when hovering over something which TS doesn't provide type info for, e.g. the `const` keyword. Not a problem though.

How do you pronounce tsuquyomi in English? :-)

**Comment by Quramy** [comment]
Tsukuyomi ( tsu-ku-yo-mi, cited as "月讀" ) is one of the gods of Japanese mythology.

**Comment by OliverJAsh** [comment]
You should add that to the README ;-)
